nameOverride: ''
fullnameOverride: ''

# Also create the service, useful to do blue/green deployments switch
createService: false
# The used release name for the used application, used for Blue/Green switch, used in selector name app.kubernetes.io/instance
applicationReleaseName: ''

annotations: {}
#  kubernetes.io/ingress.class: nginx
#  kubernetes.io/tls-acme: "true"

hostsGroups: []
#  - name: <name>
#    annotations: {} # optional additional annotations
#    hosts:
#      - <chart-example.local>

tls: {}
# secretNamePrefix: tls- # optional

paths: {}
#  <name>:
#    path: <path>
#    serviceRelease: <optional release>
#    serviceName: <service name (in the release)>
#    servicePort: <service port (default to 80)>
