apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values ) | nindent 4 }}
data:
  WEB_HOST: {{ ( index ( index .Values.hostsGroup 0 ).hosts 0 ) }}
