{{- $fullName := include "common.fullname" ( dict "root" . "service" .Values ) -}}
{{- range $ingress_host_group := .Values.hostsGroups }}
---
{{- if semverCompare ">=1.19.0" ( trimPrefix "v" $.Capabilities.KubeVersion.Version ) }}
apiVersion: networking.k8s.io/v1
{{- else -}}
{{- if semverCompare ">=1.14-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ $ingress_host_group.name }}
  {{- if $ingress_host_group.annotations }}
  {{- include "common.metadata" ( dict "root" $ "service" ( dict "labels" $.Values.labels "annotations" ( merge ( dict ) $ingress_host_group.annotations $.Values.annotations ) ) $.Values ) | nindent 2 }}
  {{- else }}
  {{- include "common.metadata" ( dict "root" $ "service" $.Values ) | nindent 2 }}
  {{- end }}
  {{- if ( default ( dict ) $.Values.traefikMiddleware ) }}
  {{- if ( default true $.Values.traefikMiddleware.enabled ) }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ $.Release.Namespace }}-{{ include "common.fullname" ( dict "root" $ "service" $.Values ) }}@kubernetescrd
  {{- end }}
  {{- end }}
spec:
# Add tls only if tls is not set to false.
# With resent version of helm it should be:
# if or ( not ( hasKey $ingress_host_group "tls" ) ) ( not ( eq $ingress_host_group.tls false ) )
# without else section.
{{- if not ( hasKey $ingress_host_group "tls" ) }}
  tls:
    - hosts:
        {{- range $ingress_host_group.hosts }}
        - {{ . }}
        {{- end }}
      {{- if $.Values.tls.secretNamePrefix }}
      secretName: {{ $.Values.tls.secretNamePrefix }}-{{ $ingress_host_group.name }}
      {{- else }}
      secretName: {{ $fullName }}-{{ $ingress_host_group.name }}
      {{- end }}
{{- else }}
{{- if not ( eq $ingress_host_group.tls false ) }}
  tls:
    - hosts:
        {{- range $ingress_host_group.hosts }}
        - {{ . }}
        {{- end }}
      {{- if $.Values.tls.secretNamePrefix }}
      secretName: {{ $.Values.tls.secretNamePrefix }}-{{ $ingress_host_group.name }}
      {{- else }}
      secretName: {{ $fullName }}-{{ $ingress_host_group.name }}
      {{- end }}
{{- end }}
{{- end }}
  rules:
    {{- range $ingress_host_group.hosts }}
    - host: {{ . }}
      http:
        paths:
        {{- range $key, $path := $.Values.paths }}
          - path: "{{ .path }}"
            {{- if semverCompare ">=1.14-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.14-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                {{- if $.Values.createService }}
                name: {{ include "common.fullname" ( dict "root" $ "service" . ) }}
                {{- else }}
                name: {{ include "ingress.serviceName" ( dict "root" $ "service" $.Values "path" . ) }}
                {{- end }}
                port:
                  number: {{ .servicePort | default 80 }}
              {{- else }}
              {{- if $.Values.createService }}
              serviceName: {{ include "common.fullname" ( dict "root" $ "service" . ) }}
              {{- else }}
              serviceName: {{ include "ingress.serviceName" ( dict "root" $ "service" $.Values "path" . ) }}
              {{- end }}
              servicePort: {{ .servicePort | default 80 }}
              {{- end -}}
        {{- end }}
    {{- end }}
{{- end }}
