name: Continuous integration

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

env:
  HAS_SECRETS: ${{ secrets.HAS_SECRETS }}

jobs:
  main:
    runs-on: ubuntu-20.04
    name: Continuous integration
    timeout-minutes: 20
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"

    strategy:
      fail-fast: true
      matrix:
        helm:
          - latest
          - 3.5.1

    steps:
      - run: docker system prune --all --force
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
        if: env.HAS_SECRETS == 'HAS_SECRETS'

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Checks
        run: c2cciutils-checks

      - name: Install helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ matrix.helm }}

      - run: helm dependency update .
      - run: helm lint .

      - name: Setup k3s/k3d
        run: c2cciutils-k8s-install

      - run: helm template --namespace=default --values=tests/values.yaml test . > tests/actual.yaml
      - run: diff --ignore-trailing-space tests/actual.yaml tests/expected.yaml
      - run: helm lint --values=tests/values.yaml .
      - run: kubectl apply -f tests/expected.yaml
      - run: kubectl delete -f tests/expected.yaml || true

      - run: helm template --namespace=default --values=tests/alt.yaml test . > tests/alt-actual.yaml
      - run: diff --ignore-trailing-space tests/alt-actual.yaml tests/alt-expected.yaml
      - run: helm lint --values=tests/alt.yaml .
      - run: kubectl apply -f tests/alt-expected.yaml
      - run: kubectl delete -f tests/alt-expected.yaml || true

      - name: Publish
        run: c2cciutils-publish
        if: matrix.helm == 'latest'
